import { parser } from '@lezer/go';
import { SyntaxNode } from '@lezer/common';
import {
  RawFiberRouteDeclaration,
  FiberAppDeclaration,
  FiberGroupDeclaration,
  FiberRouteCallbackDeclaration,
  FiberMountDeclaration,
  FiberFunctionDecl,
  FiberFunctionCall,
  FiberFileAnalysisResult,
} from './types';
import { HttpMethod, isHttpMethod, HTTP_METHODS } from '../../models/HttpMethod';
import { RouteConfidence } from '../../models/RouteConfidence';

const FIBER_SHORTHAND_METHODS = new Map<string, HttpMethod>([
  ['get', 'GET'],
  ['post', 'POST'],
  ['put', 'PUT'],
  ['patch', 'PATCH'],
  ['delete', 'DELETE'],
  ['head', 'HEAD'],
  ['options', 'OPTIONS'],
  ['trace', 'TRACE'],
]);

// All 8 canonical Route Peek HTTP methods generated by Fiber .All()
const FIBER_ALL_METHODS: readonly HttpMethod[] = HTTP_METHODS;

interface PathResolution {
  readonly path: string;
  readonly confidence: RouteConfidence;
  readonly isDynamic?: boolean;
}

function getLineAndColumn(source: string, offset: number): { line: number; column: number } {
  const clamped = Math.max(0, Math.min(offset, source.length));
  let line = 1;
  let lineStart = 0;
  for (let i = 0; i < clamped; i++) {
    if (source[i] === '\n') {
      line++;
      lineStart = i + 1;
    }
  }
  const column = clamped - lineStart + 1;
  return { line, column };
}

function stripQuotes(str: string): string {
  if ((str.startsWith('"') && str.endsWith('"')) || (str.startsWith('`') && str.endsWith('`'))) {
    return str.slice(1, -1);
  }
  return str;
}

/**
 * Checks if a type expression denotes a Fiber App or Fiber Router.
 * Rules:
 * - App is a struct, referenced via pointer *fiber.App, *(alias).App, *App, or value fiber.App, App.
 * - Router is an interface in Fiber, referenced by value fiber.Router, (alias).Router, Router.
 * - Per user constraint #2, *fiber.Router is NOT valid for the interface and must be rejected.
 */
export function isFiberAppOrRouterType(typeText: string): boolean {
  const cleaned = typeText.trim();
  // Reject pointer to Router: *fiber.Router or *Router
  if (cleaned.includes('*') && cleaned.includes('Router')) {
    return false;
  }
  // Fiber App: *fiber.App, fiber.App, *App, App
  if (/^\*?(\w+\.)?App$/.test(cleaned)) {
    return true;
  }
  // Fiber Router: fiber.Router, Router
  if (/^(\w+\.)?Router$/.test(cleaned)) {
    return true;
  }
  return false;
}

export class FiberAnalyzer {
  public analyzeFile(
    relativePath: string,
    absolutePath: string,
    content: string
  ): FiberFileAnalysisResult {
    const normRel = relativePath.replace(/\\/g, '/');
    const warnings: string[] = [];
    const errors: string[] = [];

    let tree;
    try {
      tree = parser.parse(content);
    } catch (err) {
      errors.push(`Failed to parse Go source: ${err instanceof Error ? err.message : String(err)}`);
      return {
        relativePath: normRel,
        absolutePath,
        packageName: '',
        imports: [],
        apps: [],
        routes: [],
        groups: [],
        mounts: [],
        routeCallbacks: [],
        functions: [],
        calls: [],
        constants: new Map(),
        errors,
      };
    }

    let packageName = '';
    const imports: { path: string; alias?: string }[] = [];
    const constants = new Map<string, string>();
    const structFiberFields = new Map<string, Set<string>>();
    let currentStructName: string | null = null;

    // 1. Pass 1: Extract package name, imports, constants, and struct types with Fiber fields
    tree.iterate({
      enter(node) {
        if (node.name === 'PackageClause') {
          const def = node.node.getChild('DefName');
          if (def) {
            packageName = content.slice(def.from, def.to);
          }
        } else if (node.name === 'ImportSpec') {
          const specNode = node.node;
          let importPath = '';
          let alias: string | undefined;

          for (let c = specNode.firstChild; c; c = c.nextSibling) {
            if (c.name === 'DefName' || c.name === 'VariableName') {
              alias = content.slice(c.from, c.to);
            } else if (c.name === 'String') {
              importPath = stripQuotes(content.slice(c.from, c.to));
            }
          }

          if (importPath) {
            imports.push({ path: importPath, alias });
          }
        } else if (node.name === 'ConstSpec') {
          const specNode = node.node;
          const def = specNode.getChild('DefName');
          const str = specNode.getChild('String');
          if (def && str) {
            const name = content.slice(def.from, def.to);
            const val = stripQuotes(content.slice(str.from, str.to));
            constants.set(name, val);
          }
        } else if (node.name === 'TypeSpec') {
          const def = node.node.getChild('DefName');
          const structType = node.node.getChild('StructType');
          if (def && structType) {
            currentStructName = content.slice(def.from, def.to);
            structFiberFields.set(currentStructName, new Set());
          }
        } else if (node.name === 'FieldDecl' && currentStructName) {
          const fieldNameNode = node.node.getChild('FieldName');
          const typeNode =
            node.node.getChild('PointerType') ||
            node.node.getChild('QualifiedType') ||
            node.node.getChild('TypeName');
          if (fieldNameNode && typeNode) {
            const typeText = content.slice(typeNode.from, typeNode.to).trim();
            if (isFiberAppOrRouterType(typeText)) {
              const fieldName = content.slice(fieldNameNode.from, fieldNameNode.to);
              structFiberFields.get(currentStructName)?.add(fieldName);
            }
          }
        }
      },
      leave(node) {
        if (node.name === 'TypeSpec') {
          currentStructName = null;
        }
      },
    });

    const apps: FiberAppDeclaration[] = [];
    const routes: RawFiberRouteDeclaration[] = [];
    const groups: FiberGroupDeclaration[] = [];
    const mounts: FiberMountDeclaration[] = [];
    const routeCallbacks: FiberRouteCallbackDeclaration[] = [];
    const functions: FiberFunctionDecl[] = [];
    const calls: FiberFunctionCall[] = [];

    // Helper to evaluate static strings / concatenation
    const resolveStringExpr = (node: SyntaxNode | null): PathResolution => {
      if (!node) {
        return { path: '<dynamic>', confidence: 'low', isDynamic: true };
      }

      if (node.name === 'String') {
        return {
          path: stripQuotes(content.slice(node.from, node.to)),
          confidence: 'high',
        };
      }

      if (node.name === 'VariableName' || node.name === 'Identifier') {
        const id = content.slice(node.from, node.to);
        if (constants.has(id)) {
          return { path: constants.get(id)!, confidence: 'high' };
        }
        return { path: '<dynamic>', confidence: 'low', isDynamic: true };
      }

      if (node.name === 'BinaryExp') {
        // e.g. a + b
        const parts: string[] = [];
        let allStatic = true;

        const collectBinary = (n: SyntaxNode) => {
          if (n.name === 'BinaryExp') {
            for (let c = n.firstChild; c; c = c.nextSibling) {
              if (c.name !== 'ArithOp') {
                collectBinary(c);
              }
            }
          } else {
            const res = resolveStringExpr(n);
            if (res.isDynamic || res.confidence === 'low') {
              allStatic = false;
            }
            parts.push(res.path);
          }
        };

        collectBinary(node);

        if (allStatic) {
          return { path: parts.join(''), confidence: 'high' };
        }
        return { path: '<dynamic>', confidence: 'low', isDynamic: true };
      }

      return { path: '<dynamic>', confidence: 'low', isDynamic: true };
    };

    // Helper to resolve slice literal or string for .Add()
    const resolveMethodsList = (node: SyntaxNode | null): string[] | null => {
      if (!node) return null;
      if (node.name === 'String') {
        return [stripQuotes(content.slice(node.from, node.to))];
      }
      if (node.name === 'TypedLiteral') {
        const val = node.getChild('LiteralValue');
        if (!val) return null;
        const methods: string[] = [];
        for (let c = val.firstChild; c; c = c.nextSibling) {
          if (c.name === 'Element') {
            const strNode = c.getChild('String') || c;
            methods.push(stripQuotes(content.slice(strNode.from, strNode.to)));
          }
        }
        return methods;
      }
      return null;
    };

    // Scope tracker for identifying Fiber router variables with lexical shadowing
    interface Scope {
      readonly vars: Map<string, boolean>; // varName -> isFiber
    }
    const scopeStack: Scope[] = [{ vars: new Map() }];

    const isFiberVar = (name: string): boolean => {
      for (let i = scopeStack.length - 1; i >= 0; i--) {
        if (scopeStack[i].vars.has(name)) {
          return scopeStack[i].vars.get(name)!;
        }
      }
      return false;
    };

    const addVar = (name: string, isFiber: boolean) => {
      scopeStack[scopeStack.length - 1].vars.set(name, isFiber);
    };

    // Check if CallExpr is a RouteChain call: e.g. root.RouteChain("/path")
    interface RouteChainInfo {
      readonly rootReceiver: string;
      readonly path: string;
      readonly confidence: RouteConfidence;
      readonly isDynamic?: boolean;
    }

    const unwindingRouteChain = (callNode: SyntaxNode): RouteChainInfo | null => {
      const sel = callNode.getChild('SelectorExpr');
      if (!sel) return null;
      const field = sel.getChild('FieldName');
      if (!field) return null;
      const method = content.slice(field.from, field.to);

      if (method === 'RouteChain') {
        const operand = sel.firstChild;
        if (!operand) return null;
        const rec = content.slice(operand.from, operand.to);
        const args = callNode.getChild('Arguments');
        let arg1: SyntaxNode | null = null;
        if (args) {
          for (let c = args.firstChild; c; c = c.nextSibling) {
            if (c.name !== '(' && c.name !== ')' && c.name !== ',') {
              arg1 = c;
              break;
            }
          }
        }
        const p = resolveStringExpr(arg1);
        return {
          rootReceiver: rec,
          path: p.path,
          confidence: p.confidence,
          isDynamic: p.isDynamic,
        };
      }

      // If operand is another CallExpr, recurse
      const operand = sel.firstChild;
      if (operand && operand.name === 'CallExpr') {
        return unwindingRouteChain(operand);
      }

      return null;
    };

    // Traverse AST to collect variables, routes, groups, mounts
    tree.iterate({
      enter(node) {
        if (
          node.name === 'Block' ||
          node.name === 'MethodDecl' ||
          node.name === 'FunctionDecl'
        ) {
          scopeStack.push({ vars: new Map() });
        }

        // Method declarations: func (c *RouteConfig) Setup() { ... }
        if (node.name === 'MethodDecl') {
          const mNode = node.node;
          const params = mNode.getChild('Parameters');
          if (params) {
            const p = params.getChild('Parameter');
            if (p) {
              const pDef = p.getChild('DefName');
              const pType =
                p.getChild('PointerType') ||
                p.getChild('QualifiedType') ||
                p.getChild('TypeName');
              if (pDef && pType) {
                const recVar = content.slice(pDef.from, pDef.to);
                const typeText = content
                  .slice(pType.from, pType.to)
                  .replace(/^\*/, '')
                  .trim();
                // Provenance check: only register fields if struct is proven to have Fiber fields
                if (structFiberFields.has(typeText)) {
                  const pos = getLineAndColumn(content, mNode.from);
                  for (const field of structFiberFields.get(typeText)!) {
                    const fullReceiverName = `${recVar}.${field}`;
                    addVar(fullReceiverName, true);
                    apps.push({
                      name: fullReceiverName,
                      file: normRel,
                      line: pos.line,
                      column: pos.column,
                    });
                  }
                }
              }
            }
          }

          // Check method parameter arguments for router types
          const fnField = mNode.getChild('FieldName');
          const fnName = fnField ? content.slice(fnField.from, fnField.to) : '';
          let argParams: SyntaxNode | null = null;
          let pCount = 0;
          for (let c = mNode.firstChild; c; c = c.nextSibling) {
            if (c.name === 'Parameters') {
              pCount++;
              if (pCount === 2) {
                argParams = c;
                break;
              }
            }
          }

          if (argParams) {
            const paramNames: string[] = [];
            for (let c = argParams.firstChild; c; c = c.nextSibling) {
              if (c.name === 'Parameter') {
                const pDef = c.getChild('DefName');
                const pType =
                  c.getChild('PointerType') ||
                  c.getChild('QualifiedType') ||
                  c.getChild('TypeName');
                if (pDef && pType) {
                  const typeText = content.slice(pType.from, pType.to);
                  if (isFiberAppOrRouterType(typeText)) {
                    const pName = content.slice(pDef.from, pDef.to);
                    paramNames.push(pName);
                    addVar(pName, true);
                  }
                }
              }
            }
            if (paramNames.length > 0 && fnName) {
              functions.push({
                name: fnName,
                paramNames,
                file: normRel,
                routes: [],
                groups: [],
                mounts: [],
                routeCallbacks: [],
              });
            }
          }
        }

        // 1. Variable declarations: app := fiber.New(), v1 := api.Group(...), or shadowed app := db.Connect()
        if (node.name === 'VarDecl') {
          const varNode = node.node;
          const def = varNode.getChild('DefName');
          const call = varNode.getChild('CallExpr');
          if (def) {
            const varName = content.slice(def.from, def.to);
            let isFiber = false;

            if (call) {
              const sel = call.getChild('SelectorExpr');
              if (sel) {
                const op = sel.firstChild;
                const field = sel.getChild('FieldName');
                if (op && field) {
                  const rec = content.slice(op.from, op.to);
                  const method = content.slice(field.from, field.to);

                  // fiber.New()
                  if (rec === 'fiber' && method === 'New') {
                    isFiber = true;
                    const pos = getLineAndColumn(content, call.from);
                    apps.push({
                      name: varName,
                      file: normRel,
                      line: pos.line,
                      column: pos.column,
                    });
                  }
                  // group := app.Group("/api") or group := c.App.Group("/api")
                  else if (isFiberVar(rec) && method === 'Group') {
                    isFiber = true;
                    const args = call.getChild('Arguments');
                    let arg1: SyntaxNode | null = null;
                    if (args) {
                      for (let c = args.firstChild; c; c = c.nextSibling) {
                        if (c.name !== '(' && c.name !== ')' && c.name !== ',') {
                          arg1 = c;
                          break;
                        }
                      }
                    }
                    const prefixRes = resolveStringExpr(arg1);
                    const pos = getLineAndColumn(content, call.from);
                    groups.push({
                      receiverName: varName,
                      parentReceiverName: rec,
                      prefix: prefixRes.path,
                      confidence: prefixRes.confidence,
                      file: normRel,
                      line: pos.line,
                      column: pos.column,
                    });
                  }
                }
              }
            }

            addVar(varName, isFiber);
          }
        }

        // 2. Call expressions: app.Get(), app.All(), app.Add(), app.Use(), app.Route(), etc.
        if (node.name === 'CallExpr') {
          const call = node.node;
          const callArgs = call.getChild('Arguments');
          const sel = call.getChild('SelectorExpr');
          if (sel) {
            const op = sel.firstChild;
            const field = sel.getChild('FieldName');
            if (op && field) {
              const fieldText = content.slice(field.from, field.to);
              const methodLower = fieldText.toLowerCase();

              // Check if chained RouteChain call
              const routeChain = unwindingRouteChain(call);
              if (routeChain && FIBER_SHORTHAND_METHODS.has(methodLower)) {
                const httpMethod = FIBER_SHORTHAND_METHODS.get(methodLower)!;
                const pos = getLineAndColumn(content, field.from);
                routes.push({
                  receiverName: routeChain.rootReceiver,
                  method: httpMethod,
                  path: routeChain.path,
                  confidence: routeChain.confidence,
                  file: normRel,
                  line: pos.line,
                  column: pos.column,
                  isDynamic: routeChain.isDynamic,
                });
                return;
              }

              const recName = content.slice(op.from, op.to);

              // Must be a known Fiber router or app
              if (isFiberVar(recName)) {
                const argNodes: SyntaxNode[] = [];
                if (callArgs) {
                  for (let c = callArgs.firstChild; c; c = c.nextSibling) {
                    if (c.name !== '(' && c.name !== ')' && c.name !== ',') {
                      argNodes.push(c);
                    }
                  }
                }

                // Shorthand methods: app.Get("/users", ...)
                if (FIBER_SHORTHAND_METHODS.has(methodLower)) {
                  if (argNodes.length >= 1) {
                    const pathRes = resolveStringExpr(argNodes[0]);
                    const pos = getLineAndColumn(content, call.from);
                    routes.push({
                      receiverName: recName,
                      method: FIBER_SHORTHAND_METHODS.get(methodLower)!,
                      path: pathRes.path,
                      confidence: pathRes.confidence,
                      file: normRel,
                      line: pos.line,
                      column: pos.column,
                      isDynamic: pathRes.isDynamic,
                    });
                  }
                }
                // app.All("/users", ...) -> expands into all 8 canonical methods
                else if (fieldText === 'All') {
                  if (argNodes.length >= 1) {
                    const pathRes = resolveStringExpr(argNodes[0]);
                    const pos = getLineAndColumn(content, call.from);
                    for (const m of FIBER_ALL_METHODS) {
                      routes.push({
                        receiverName: recName,
                        method: m,
                        path: pathRes.path,
                        confidence: pathRes.confidence,
                        file: normRel,
                        line: pos.line,
                        column: pos.column,
                        isDynamic: pathRes.isDynamic,
                      });
                    }
                  }
                }
                // app.Add([]string{"GET", "POST"}, "/users", ...)
                else if (fieldText === 'Add') {
                  if (argNodes.length >= 2) {
                    const rawMethods = resolveMethodsList(argNodes[0]);
                    const pathRes = resolveStringExpr(argNodes[1]);
                    const pos = getLineAndColumn(content, call.from);
                    if (rawMethods && rawMethods.length > 0) {
                      for (const rm of rawMethods) {
                        const upper = rm.toUpperCase().trim();
                        if (isHttpMethod(upper)) {
                          routes.push({
                            receiverName: recName,
                            method: upper,
                            path: pathRes.path,
                            confidence: pathRes.confidence,
                            file: normRel,
                            line: pos.line,
                            column: pos.column,
                            isDynamic: pathRes.isDynamic,
                          });
                        }
                      }
                    }
                  }
                }
                // app.Route("/users", func(router fiber.Router) { ... })
                else if (fieldText === 'Route') {
                  if (argNodes.length >= 2) {
                    const prefixRes = resolveStringExpr(argNodes[0]);
                    const fnLit = argNodes[1];
                    if (fnLit.name === 'FunctionLiteral') {
                      const params = fnLit.getChild('Parameters');
                      if (params) {
                        const param = params.getChild('Parameter');
                        if (param) {
                          const pDef = param.getChild('DefName');
                          if (pDef) {
                            const pName = content.slice(pDef.from, pDef.to);
                            addVar(pName, true);
                            const pos = getLineAndColumn(content, call.from);
                            routeCallbacks.push({
                              parentReceiverName: recName,
                              paramRouterName: pName,
                              prefix: prefixRes.path,
                              confidence: prefixRes.confidence,
                              file: normRel,
                              line: pos.line,
                              column: pos.column,
                            });
                          }
                        }
                      }
                    }
                  }
                }
                // app.Use("/prefix", subApp) or app.Mount("/prefix", subApp)
                else if (fieldText === 'Use' || fieldText === 'Mount') {
                  if (argNodes.length >= 2) {
                    const arg0Res = resolveStringExpr(argNodes[0]);
                    // Check if 2nd argument is a known Fiber app
                    const arg1 = argNodes[1];
                    if (arg1.name === 'VariableName' || arg1.name === 'Identifier') {
                      const subAppName = content.slice(arg1.from, arg1.to);
                      if (isFiberVar(subAppName) && !arg0Res.isDynamic) {
                        // Confirmed sub-app mounting!
                        const pos = getLineAndColumn(content, call.from);
                        mounts.push({
                          parentReceiverName: recName,
                          subAppReceiverName: subAppName,
                          prefix: arg0Res.path,
                          confidence: arg0Res.confidence,
                          file: normRel,
                          line: pos.line,
                          column: pos.column,
                        });
                      }
                    }
                  }
                }
              }

              // Function call passing a Fiber router: e.g. routes.Register(app) or Setup(c.App)
              if (callArgs) {
                for (let c = callArgs.firstChild; c; c = c.nextSibling) {
                  if (
                    c.name === 'VariableName' ||
                    c.name === 'Identifier' ||
                    c.name === 'SelectorExpr'
                  ) {
                    const argName = content.slice(c.from, c.to);
                    if (isFiberVar(argName)) {
                      const pos = getLineAndColumn(content, call.from);
                      calls.push({
                        functionName: fieldText,
                        packageName: recName !== argName ? recName : undefined,
                        passedReceiverName: argName,
                        file: normRel,
                        line: pos.line,
                        column: pos.column,
                      });
                    }
                  }
                }
              }
            }
          } else {
            // Direct function call in the same package: e.g. SetupAuthRoutes(api)
            const fnIdent = call.firstChild;
            if (fnIdent && (fnIdent.name === 'VariableName' || fnIdent.name === 'Identifier')) {
              const fnName = content.slice(fnIdent.from, fnIdent.to);
              if (callArgs) {
                for (let c = callArgs.firstChild; c; c = c.nextSibling) {
                  if (
                    c.name === 'VariableName' ||
                    c.name === 'Identifier' ||
                    c.name === 'SelectorExpr'
                  ) {
                    const argName = content.slice(c.from, c.to);
                    if (isFiberVar(argName)) {
                      const pos = getLineAndColumn(content, call.from);
                      calls.push({
                        functionName: fnName,
                        passedReceiverName: argName,
                        file: normRel,
                        line: pos.line,
                        column: pos.column,
                      });
                    }
                  }
                }
              }
            }
          }
        }

        // 3. Function declarations: func Setup(app *fiber.App) { ... }
        if (node.name === 'FunctionDecl') {
          const fnNode = node.node;
          const fnDef = fnNode.getChild('DefName');
          const params = fnNode.getChild('Parameters');
          if (fnDef && params) {
            const fnName = content.slice(fnDef.from, fnDef.to);
            const paramNames: string[] = [];

            for (let c = params.firstChild; c; c = c.nextSibling) {
              if (c.name === 'Parameter') {
                const pDef = c.getChild('DefName');
                const pType =
                  c.getChild('PointerType') ||
                  c.getChild('QualifiedType') ||
                  c.getChild('TypeName');
                if (pDef && pType) {
                  const typeText = content.slice(pType.from, pType.to);
                  if (isFiberAppOrRouterType(typeText)) {
                    const pName = content.slice(pDef.from, pDef.to);
                    paramNames.push(pName);
                    addVar(pName, true);
                  }
                }
              }
            }

            if (paramNames.length > 0) {
              functions.push({
                name: fnName,
                paramNames,
                file: normRel,
                routes: [],
                groups: [],
                mounts: [],
                routeCallbacks: [],
              });
            }
          }
        }
      },
      leave(node) {
        if (
          node.name === 'Block' ||
          node.name === 'MethodDecl' ||
          node.name === 'FunctionDecl'
        ) {
          scopeStack.pop();
        }
      },
    });

    // Sort routes deterministically by source location
    routes.sort((a, b) => (a.line !== b.line ? a.line - b.line : a.column - b.column));

    return {
      relativePath: normRel,
      absolutePath,
      packageName,
      imports,
      apps,
      routes,
      groups,
      mounts,
      routeCallbacks,
      functions,
      calls,
      constants,
      warnings: warnings.length > 0 ? warnings : undefined,
      errors: errors.length > 0 ? errors : undefined,
    };
  }
}
